controller_names:
  - arm_controller
  - gripper_controller

arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
gripper_controller:
  type: GripperCommand
  action_ns: gripper_cmd
  default: true
  joints:
    - gripper_left_joint

